const express = require("express");
const cors = require("cors");
const { OpenAI } = require("openai");
require("dotenv").config();
const path = require("path");

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

const client = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

// 🧠 MEMORY (per user session – simple)
let memory = [
  {
    role: "system",
    content:
      "You are MÎK AI, a futuristic, professional assistant created by Jani. Be helpful, intelligent, and friendly.",
  },
];

app.get("/", (req, res) => {
  res.sendFile(path.join(__dirname, "public", "index.html"));
});

app.post("/chat", async (req, res) => {
  try {
    const message = req.body.message;
    const lower = message.toLowerCase();

    // 🖼️ IMAGE GENERATION (FREE & WORKING)
    if (
      lower.includes("draw") ||
      lower.includes("generate image") ||
      lower.includes("image") ||
      lower.includes("picture")
    ) {
      const seed = Math.floor(Math.random() * 999999);
      const imageUrl = `https://pollinations.ai/p/${encodeURIComponent(
        message
      )}?width=1024&height=1024&seed=${seed}&model=flux`;

      return res.json({
        type: "image",
        text: "🎨 Image generated by MÎK AI",
        image: imageUrl,
      });
    }

    // 🧠 ADD TO MEMORY
    memory.push({ role: "user", content: message });

    // LIMIT MEMORY (important)
    if (memory.length > 12) {
      memory = memory.slice(-12);
    }

    const response = await client.chat.completions.create({
      model: "gpt-4o",
      messages: memory,
    });

    const reply = response.choices[0].message.content;

    memory.push({ role: "assistant", content: reply });

    res.json({
      type: "text",
      reply,
    });
  } catch (err) {
    console.error(err);
    res.status(500).json({
      type: "text",
      reply: "⚠️ MÎK AI is overloaded. Try again.",
    });
  }
});

const PORT = process.env.PORT || 10000;
app.listen(PORT, () =>
  console.log(`🚀 MÎK AI running on port ${PORT}`)
);
